# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ebcb1898f8337b9e30a3175c8849029c7cb1ecce1c138c8e9a7cd6bdc7c8dfa0ccb75a73c338ad5a2c7ccb161b62aac673d5f96792fba098422199d8d160ea1

test:
  secret_key_base: 4c362dbb1d2aefb27ae1e68cced6d4ffa4036c3c1744179ac3fa867fad316b2a4f7c94e85ab800df4310333daa509ca154a1f4f91c591ece42d6e16bb3c64ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
